# -*- coding: utf-8 -*-
"""irving.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbZDw7djC5d0vnVf8DCc8O3AhdLM7fIn
"""



"""Do all the environment stuff in 1 cell, to avoid variable pain...


---


"""

import os
import sys
from google.colab import drive
#drive.mount('/content/drive')
nbp="/content/drive/My Drive/Colab Notebooks"
sys.path.insert(0,nbp)
os.chdir(nbp)
!pwd

# Commented out IPython magic to ensure Python compatibility.
!pwd
print("----------------")
# %ls
print("----------------\n")
# %cat caller.py
print("XXXXXXXXXXXXXXXXXXXXXXX")
# %run caller.py
print("XXXXXXXXXXXXXXXXXXXXXXX")