
name: Run Python Test for Face Detection
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
            python-version: 3.12
            node-version: 20
      - name: Cache pip dependencies
        uses: actions/cache@v2
            
        with:
            node-version: 20
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/FaceDetection/src/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r FaceDetection/src/requirements.txt
          echo "GITHUB_ENV $GITHUB_ENV"
          cat $GITHUB_ENV
      - name: set pythonpath
        run: echo "PYTHONPATH=./FaceDetection" >> $GITHUB_ENV
      - name: pytest Face Detection
        run: pytest FaceDetection/test/test_FaceDetector.py -vv -s
        