name: Run Python Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U mock
          pip install pytest-mock
          echo "GITHUB_ENV $GITHUB_ENV"
          cat $GITHUB_ENV
      - name: set pythonpath
        run: echo "PYTHONPATH=." >> $GITHUB_ENV
      - name: pytest DocumentHandling
        run: pytest DocumentHandling -v -s
      - name: pytest ImageHandling - exif
        run: pytest ImageHandling/exif -v -s
      - name: pytest Utilties
        run: pytest Utilities -v -s
                
        
